a= float(input('ENTER AMOUNT IN DOLLARS: '))
print('THE CHANGE IS ')
b=int(a/50)
print(b,'fifties')
remainder1=float(a%50)
c=int(remainder1/20)
print(c,'twenties')
remainder2= float(remainder1%20)
d=int(remainder2/10)
print(d,'tens')
remainder3=float(remainder2%10)
e=int(remainder3/5)
print(e,'fives')
remainder4=float(remainder3%5)
f=int(remainder4/0.25)
print(f,'quarter')
remainder5=float(remainder4%0.25)
g=int(remainder4/0.1)
print(g,'dimes')
remainder6=float(remainder5%0.1)
h=int(remainder6/0.05)
print(h,'nickels')
remainder7=float(remainder6%0.05)
i=int(remainder7/0.01)
print(i,'pennies')


